### ISSUE TITLE
Users Are Alerted To Losing Unsaved Changes

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/code-journal#10]
## 💰 Motivation

Users sometimes may inadvertently click away from a filled out form before saving, resulting in their inputs being lost. The web page should notify users that their data may be lost before navigating them away.

## 📐 Plan

Create a pop-up alert if there are unsaved changes on a form and the view is about to change.

## ✅ Task List

- [ ] Check if a new entry form has been filled out at all.
- [ ] Create function to show a pop-up alert that pauses a view swap. If the user clicks confirm, continue with the view swap. Otherwise, remain on the same page with no input values changed.
- [ ] Check if an edit entry form differs from the original.
- [ ] In the event listener for the Entries nav button, add a check for unsaved/unsubmitted changes and code to show the alert.
- [ ] Try code in incognito window.
- [ ] Fix bugs.
- [ ] Bonus: Incorporate checks for page unloading.
