### ISSUE TITLE
Basic Features Optimization

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/code-journal#11]
## 💰 Motivation

While cleaner and more logically sound code does not directly affect the user, it allows for easier and faster updates. This translates into more features more often for users.

## 📐 Plan

Update codebase to substitute hard-coded values for variables and make functions more generalizable while maintaining all of the same functionality, without serious impact to performance. Additionally, add some small, decorative details to make the page feel more responsive.

## ✅ Task List

- [x] Add `data-view` attributes to anchor elements/buttons for view swapping.
- [x] Swap views using `data-view` attributes rather than hard coding values into conditions.
- [x] Separate out full DOM tree rendering code from view swap function.
- [x] Persist DOM tree of entries rather than regenerating from scratch every time.
- [x] Add conditional logic to update or insert new entry DOM trees.
- [x] Reduce/eliminate referencing globally scoped objects in functions
- [ ] Bonus: Put hover behavior on links/buttons/icons so they appear more "clickable"
- [x] Bonus: Put transition on delete modal to make it appear like it is "popping up"
- [x] Bonus: Allow users to click "Code Journal" text in header to also return to the Entries view.

**Comment by dennisliu9** [comment]
![delete-modal-transition_feature](https://user-images.githubusercontent.com/21215658/171762267-8c7412d1-8c12-4471-8ab5-7169dedc2e46.gif)

A cheesy transition, but a good learning exercise.
