### ISSUE TITLE
User Can Toggle Dark Mode

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/code-journal#9]
## 💰 Motivation

Some users find webpages with darker color schemes to be more comfortable, so they should be able to toggle between a regular color scheme and a darker color scheme.

## 📐 Plan

Allow users to toggle between a dark mode and a light mode, and have an additional auto option that detects system preference.

## 🖼️ Wireframes
![darkmode_example](https://user-images.githubusercontent.com/21215658/171517905-026e3940-8e7f-4bd5-b6a0-2b7bd0e94cf1.png)

## ✅ Task List

- [x] Add a dark mode toggle icon to the top right of the nav bar
- [x] Create CSS rulesets for dark and light class selectors, and declare rules for colors
- [x] Create custom properties/variables for colors and apply them to the rest of the CSS rulesets
- [x] Add an event listener to the dark mode toggle icon that sets the class of the `html` element to either dark or light
- [x] Add visual indication of which color mode has been chosen
- [ ] Add media rule to detect system preference for color scheme and set user's system preference as the default mode
- [ ] Change toggle to a dropdown with the `select` element
- [ ] Bonus: Persist dark mode toggle choice to `localStorage` and retrieve it when loading the page
- [x] Bonus: Lower the brightness of images when in dark mode using a filter
- [ ] Remove unnecessary CSS
- [ ] Test in an incognito window
- [ ] Fix bugs

**Comment by dennisliu9** [comment]
![dark-mode_preliminary_feature](https://user-images.githubusercontent.com/21215658/171825359-b9dd491b-3d12-41ae-8145-313b074ccaf6.gif)

Gif of preliminary attempt at dark mode toggle.

**Comment by dennisliu9** [comment]
![dark-mode_light-effect_feature](https://user-images.githubusercontent.com/21215658/172079719-b797803a-6e0e-4c98-8340-c3ddf667f376.gif)

Visual changes to toggle
